# Generated by Django 5.2 on 2025-04-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='cointransaction',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
    ]
