# Generated by Django 5.2 on 2025-04-05 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cointransaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointransaction',
            name='transaction_type',
            field=models.CharField(choices=[('referral_bonus', 'Referral Bonus'), ('withdrawal', 'Withdrawal'), ('recycling_reward', 'Recycling Reward')], max_length=20),
        ),
        migrations.CreateModel(
            name='RecyclableUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='recyclables/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
