# Generated by Django 5.2 on 2025-04-05 17:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_cointransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclableupload',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
