# Generated by Django 5.2 on 2025-04-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_companyprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointransaction',
            name='transaction_type',
            field=models.CharField(choices=[('referral_bonus', 'Referral Bonus'), ('withdrawal', 'Withdrawal'), ('recycling_reward', 'Recycling Reward'), ('indirect_referral_bonus', 'indirect referral bonus')], max_length=50),
        ),
    ]
