# Generated by Django 5.2 on 2025-04-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_cointransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='valid_coins',
            field=models.IntegerField(default=0),
        ),
    ]
